# Generated by Django 3.0.8 on 2020-07-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200715_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['id']},
        ),
    ]
